version: 2
# GoReleaser configuration for gormdb2struct
# See: https://goreleaser.com/

project_name: gormdb2struct

dist: dist

before:
  hooks:
    - go mod tidy

# Build the CLI for linux and windows
builds:
  - id: cli-multiplatform
    main: .
    binary: gormdb2struct
    env:
      - CGO_ENABLED=0
    goos: [linux, windows]
    goarch: [amd64, arm64]
    ldflags:
      - -s -w
      - -X main.version={{ .Version }}
      - -X main.commit={{ .ShortCommit }}
      - -X main.date={{ .Date }}
    flags:
      - -trimpath

  # Separate build specifically for macOS to be used by the Homebrew Cask
  - id: cli-macos
    main: .
    binary: gormdb2struct
    env:
      - CGO_ENABLED=0
    goos: [darwin]
    goarch: [amd64, arm64]
    ldflags:
      - -s -w
      - -X main.version={{ .Version }}
      - -X main.commit={{ .ShortCommit }}
      - -X main.date={{ .Date }}
    flags:
      - -trimpath

# Package archives and include common files
archives:
  - id: archives-multiplatform
    files:
      - LICENSE
      - README.md
    format_overrides:
      - goos: windows
        formats: [ 'zip' ]
    ids:
      - cli-multiplatform

  - id: archives-macos
    files:
      - LICENSE
      - README.md
    ids:
      - cli-macos

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^chore:'

# Create RPM packages (dnf/yum) using nfpm
nfpms:
  - id: rpm
    package_name: gormdb2struct
    file_name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    homepage: https://github.com/dan-sherwin/gormdb2struct
    description: Generate strongly typed GORM models and query helpers from your database schema.
    maintainer: Dan Sherwin
    license: MIT
    vendor: Dan Sherwin
    formats:
      - rpm
    ids:
      - cli-multiplatform
    bindir: /usr/bin
    rpm:
      summary: GORM database-to-struct generator
      group: Development/Tools

release:
  draft: false
  prerelease: '{{ if .Prerelease }}true{{ else }}false{{ end }}'

homebrew_casks:
  - name: gormdb2struct
    ids: [archives-macos] # Link to the new macOS-specific archive
    repository:
      owner: dan-sherwin
      name: homebrew-tap
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    homepage: https://github.com/dan-sherwin/gormdb2struct
    description: "Generate strongly typed GORM models and query helpers from your database schema."
    license: MIT
    commit_author:
      name: GoReleaser Bot
      email: noreply@github.com