name: Publish YUM Repo

on:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  yum-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download release RPM assets
        uses: robinraju/release-downloader@v1.11
        with:
          repository: ${{ github.repository }}
          tag: ${{ github.event.release.tag_name }}
          fileName: "gormdb2struct_*_linux_*.rpm"
          out-file-path: dist_rpms

      - name: Install createrepo_c
        run: sudo apt-get update && sudo apt-get install -y createrepo-c

      - name: Prepare repo directories
        run: |
          mkdir -p public/rpm/x86_64 public/rpm/aarch64
          shopt -s nullglob
          for f in dist_rpms/*linux_amd64.rpm; do cp "$f" public/rpm/x86_64/; done
          for f in dist_rpms/*linux_arm64.rpm; do cp "$f" public/rpm/aarch64/; done

      - name: Create repodata
        run: |
          createrepo_c public/rpm/x86_64
          createrepo_c public/rpm/aarch64

      - name: Add index
        run: |
          cat > public/index.html <<'EOF'
          <html><body>
          <h1>gormdb2struct YUM Repo</h1>
          <p>Architectures:</p>
          <ul>
            <li><a href="/gormdb2struct/rpm/x86_64/">x86_64</a></li>
            <li><a href="/gormdb2struct/rpm/aarch64/">aarch64</a></li>
          </ul>
          </body></html>
          EOF

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public
